### ISSUE TITLE
Plugin delete leading spaces after switching

### ISSUE THREAD

**Issue by myshov** [sagarrakshe/toggle-bool#1]
For example, there is this string (see there is space after equal sign):

```
exports['someOption'] = false;
```

after `<leader>r` on `false`, all space before false will be deleted:

```
exports['someOption'] =true;
```

I think there should no be any deleting because it affect existing code formatting.

**Comment by sagarrakshe** [comment]
Fixed.

**Comment by myshov** [comment]
Thank you!
